name: "test-goactions"
description: "test-goactions"
inputs:
  command:
    description: "args"
    required: true
    default: "test"
  action:
    description: "args"
    required: true
    default: "test"
  flags:
    description: "args"
    required: true
    default: "test"
runs:
  using: docker
  image: Dockerfile
  args:
  - "${{ inputs.command }}"
  - "${{ inputs.action }}"
  - "${{ inputs.flags }}"
branding:
    color: "blue"
    icon: "code"