name: "test-goactions"
description: "test-goactions"
inputs:
  command:
    description: "args"
    required: true
    default: "test"
  action:
    description: "args"
    required: true
    default: "test"
  name:
    description: "args"
    required: true
    default: "test"
  age:
    description: "args"
    required: true
    default: "test"
runs:
  using: docker
  image: Dockerfile
  args:
  - "${{ inputs.command }}"
  - "${{ inputs.action }}"
  - "--name=${{ inputs.name }}"
  - "--age=${{ inputs.age }}"
branding:
    color: "blue"
    icon: "code"